python3 -m meshsuggestlib \
  --output_dir model/ \
  --model_dir model/checkpoint-80000/ \
  --method Semantic-BERT \
  --tokenizer_name_or_path biobert-v1.1/ \
  --dataset CLEF-2017 \
  --semantic_model_path model/PubMed-w2v.bin \
  --cache_dir cache/ \
  --output_file result/out.tsv \
  --evaluate_run \
  --qrel_file data/clef-tar-processed/CLEF-2017/testing/data/qrels \
  --email wshuai190@gmail.com
